name: oh-bother
version: 0.3.6
author: Matt Chun-Lum
about: |
  Simple* JIRA interrupt helpers.

  Currently supports issue discovery, creation, and raw JQL queries.

  *Nothing involving an atlassian api is ever simple

global_settings:
  - ColoredHelp

settings:
  - SubcommandRequiredElseHelp

args:
  - debug:
      help: Enable debugging
      long: debug
  - open:
      help: "Open in browser (enabled by default if set to true in config file)"
      short: o
      long: open
      global: true

# there is a special "config" arg that is added in the app
# itself since it requires a dynamic path value
subcommands:
  - setup:
      about: Create a config file

  - list:
      about: Lists open interrupts

  - current:
      about: Lists open interrupts assigned to you

  - next:
      about: Lists available interrupts

  # - start:
  #     about: Start work on the specified interrupt
  #     args:
  #       - issue:
  #           help: issue key
  #           index: 1
  #           required: true

  # - stop:
  #     about: Stop work on the specified interrupt
  #     args:
  #       - issue:
  #           help: issue key
  #           index: 1
  #           required: true

  # - close:
  #     about: Close the specified interrupt
  #     args:
  #       - issue:
  #           help: issue key
  #           index: 1
  #           required: true

  - new:
      about: Create a new interrupt
      after_help: |
        The following are some general usage examples (using the long option names)
            ob new 'foo'
            ob new 'foo' --description 'my description'
            ob new 'foo' --long-description
            ob new 'foo' --assignee 'bob'
            ob new 'foo' --project BAZ
            ob new 'foo' --label bar --label baz
      args:
        - summary:
            help: The summary for the new interrupt
            index: 1
            required: true
        - description:
            help: The description (conflicts with -D)
            short: d
            long: description
            takes_value: true
            conflicts_with: long_description
        - long_description:
            help: Write description in $EDITOR (conflicts with -d)
            short: D
            long: long-description
            conflicts_with: description
        - assignee:
            help: The assignee (defaults to value in config file)
            short: a
            long: assignee
            takes_value: true
        - label:
            help: Issue label (can be specified multiple times) (defaults to value in config file)
            short: l
            long: label
            multiple: true
            takes_value: true
        - issue_type:
            help: The issue_type (defaults to value in config file)
            short: i
            long: issue-type
            takes_value: true
        - extra_fields:
            help: Extra fields (can be specified multiple times, colon seperated) (defaults to hash value in config file)
            long: extra-fields
            multiple: true
            takes_value: true
        - project:
            help: The project key (defaults to value in config file)
            short: p
            long: project
            takes_value: true

  - issue:
      about: Look up an issue by it's key
      args:
        - issue:
            help: issue key
            index: 1
            required: true

  - jql:
      about: Execute a raw jql query
      args:
        - query:
            help: The JQL query
            index: 1
            required: true
        - url:
            help: Display urls
            long: url
            short: u
        - interactive:
            help: "Allow for selecting an issue"
            short: i
            long: interactive
